### ISSUE TITLE
Failed to find the "build-lambda-zip" utility. This program is required to maintain Linux file permissions in the zip archive.

### ISSUE THREAD

**Issue by ToshiWani** [aws/aws-extensions-for-dotnet-cli#101]
Hello,

Before I run the command, `dotnet lambda deploy-function` from powershell, I need to reinstall Amazon.Lambda.Tools by running `dotnet tool update -g Amazon.Lambda.Tools` command, even though the tool is already updated.  Otherwise, the tool throws error, **Failed to find the "build-lambda-zip" utility. This program is required to maintain Linux file permissions in the zip archive.**

Obviously, the version of the tool is always latest '3.3.1'

Are there any way to permanently install "build-lambda-zip" utility without reinstalling the tool?

Thank you!

**Comment by klaytaybai** [comment]
So long as you have a compatible build-lambda-zip.exe in your Amazon.Lambda.Tools resources, you should be okay.  However, you shouldn't assume that the version will never change.  Updating is the recommended way to go.

Here is an example filepath where the zip utility should live for version 3.3.1:
`~/.dotnet/tools/.store/amazon.lambda.tools/3.3.1/amazon.lambda.tools/3.3.1/tools/netcoreapp2.1/any/Resources/build-lambda-zip.exe`

**Comment by davek6887** [comment]
I have the same problem. I always have to run the update (dotnet tool update -g Amazon.Lambda.Tools) otherwise I get that error "Are there any way to permanently install "build-lambda-zip" utility without reinstalling the tool?

It feels like everytime I run the "dotnet lambda deploy-serverless" it someone is removing the lambda-zip utility.
