### ISSUE TITLE
Wrong message when trying to deploy app without binded environment

### ISSUE THREAD

**Issue by michalzubkowicz** [aws/aws-extensions-for-dotnet-cli#147]
Regarding that  issue:
https://github.com/aws/aws-extensions-for-dotnet-cli/issues/146

## Description
When I'm trying to deploy app without binded environment, or that environment which is binded to another app misleading message " Error creating environment: Environment AppApp-env already exists". It should be more brief like "Error creating environment: Environment AppApp-env already exists, please check that selected app and environment pair is binded", or something like that. 

## Reproduction Steps
Create in GUI app named App1 in environment App1, try to deploy App2 in Environment App1 like:
dotnet eb deploy-environment --environment App1 --application App2

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @michalzubkowicz,

Thanks for reporting this issue. At first glance, this appears to be a feature request or a minor bug, that requires change in error description returned by the .NET CLI command. In most cases, the .NET SDK would simply propagate the error returned by service. I will have a look at it and would update you accordingly.

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
Looking at the code, here is the high level flow for [DeployEnvironmentCommand](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/src/Amazon.ElasticBeanstalk.Tools/Commands/DeployEnvironmentCommand.cs#L440) (as per code):

1. The code determines if the application exists at the line https://github.com/aws/aws-extensions-for-dotnet-cli/blob/31c8e63d18e2a3145a28b876fbe05bb5d4cc0454/src/Amazon.ElasticBeanstalk.Tools/Commands/DeployEnvironmentCommand.cs#L96

2. If application exists, then it gets environment description at the line https://github.com/aws/aws-extensions-for-dotnet-cli/blob/31c8e63d18e2a3145a28b876fbe05bb5d4cc0454/src/Amazon.ElasticBeanstalk.Tools/Commands/DeployEnvironmentCommand.cs#L97

3. If the environment description is not `null`, it updates the environment, else it creates the new environment at line https://github.com/aws/aws-extensions-for-dotnet-cli/blob/31c8e63d18e2a3145a28b876fbe05bb5d4cc0454/src/Amazon.ElasticBeanstalk.Tools/Commands/DeployEnvironmentCommand.cs#L245

In the current scenario, the environment already exists. But since it is a new application, the logic does not retrieve the environment description. Hence, it tries to create an environment which already exists and subsequently throws the exception at the line https://github.com/aws/aws-extensions-for-dotnet-cli/blob/31c8e63d18e2a3145a28b876fbe05bb5d4cc0454/src/Amazon.ElasticBeanstalk.Tools/Commands/DeployEnvironmentCommand.cs#L440

The exception message is returned by the service, not by the .NET SDK. The service could return just any error (may be some issue with the region, and so forth). .NET SDK just reports the error to user.

@michalzubkowicz Based on above analysis, the exception is returned by the service, not the .NET SDK code. If the above explanation provides necessary input, please confirm if we could close this issue.

I do see that you are trying to deploy multiple applications in a single environment. You may refer to page [Multiple Application Support for .NET and Elastic Beanstalk](https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/deployment-beanstalk-multiple-application.html) in AWS Toolkit for Visual Studio user guide for this scenario. But note that in the example, the application types are similar and have common environment. Perhaps, this is the reason on why .NET CLI might not support multiple applications per environment out of the box.

Thanks,
Ashish

**Comment by michalzubkowicz** [comment]
Hi @ashishdhingra , thank you very much for datailed explanation. I also analyzed source code, what led me to solution, but detecting such situation and providing correct message can save someone's day and save frustration. I was able to analyze the code, but some people will not. 

I think there is a place for improvment here, but such explanation left here should be sufficient for someone in future. Thank you very much.
