### ISSUE TITLE
Question - How to run AWS Lambda Deploy task without accessing source code(or csproj)?

### ISSUE THREAD

**Issue by melih154** [aws/aws-extensions-for-dotnet-cli#23]
Hi there,

Looking ways to run AWS Lambda Deploy task without accessing source code(or csproj)?

Current Build definitions(using VSTS) requires to copy the source code(or csproj) file to artifacts and Release pipeline(using VSTS) to call AWS Lambda Deploy task, which calls dotnet lambda deploy-serverless that runs dotnet build.

- Any way to remove the necessity to remove the requirement to source code(or csproj file) to AWS Lambda Deploy task?

- Any timeline for the .Net Core 2.1 Global Tools Support? Guessing that will be the one of the main purpose of that command line tool.

**Comment by steveataws** [comment]
For the question about moving source code around, we'll be releasing a v1.1.0 update of the VSTS tools shortly (next 24/48 hours, assuming no last minutes disasters!) that update the Lambda .NET Core Deployment task to support a packaging-only mode, for both Lambda function and serverless application projects. This enables you to do the packaging as part of your build, and then publish the package in a separate release pipeline.

For a Lambda function, the release pipeline publishes the package using the general purpose Lambda Deployment task (which now also supports the .NET Core 2.1 runtime). For a serverless application project the build packaging phase uploads the code to S3 for you and updates the CodeUri properties in the template. Your build then publishes the updated template artifact and in the release pipeline you use the CloudFormation Create/Update Stack task, supplying the template artifact, to do the actual deployment.

No more copying around source code/project files :-)

**Comment by melih154** [comment]
Thanks @steveataws. Found out that update has been released, already started playing with it.

When will dotnet lambda CLI supports Global Tool, as mentioned in [the anouncement](https://aws.amazon.com/blogs/developer/aws-lambda-net-core-2-1-support-released/)?

    

Can you please confirm if below my understanding of dotnet lambda CLI support of Global Tools is correct?


1. Build Definition: Source code will not be needed to be copied
2. Release Definition: Install dotnet lambda CLI global tool Eg `dotnet tool install -g dotnetsay`
3. Release Definition: AWS Lambda Deployment task runs `dotnet lambda deploy-serverless` command, without requirement to reference Path to Lambda Project, passing `--package` parameter shall be enough.

Within the AWS Lambda .Net Core 2.1 announcement

**Comment by steveataws** [comment]
Norm is going to comment on the ETA and work for global tools.

Regarding Q3, you won't use the Lambda .NET Core Deployment task in your release pipeline. Instead (since you are using a serverless app?) you'll use the CloudFormation Create/Update Stack task. I'll have a blog post out in a couple days explaining the process for both functions and serverless apps but in summary:

**Build pipeline**
* Use Lambda .NET Core Deployment task selecting serverless app mode and 'package only' option. This will upload your code to S3 (give the task the bucket name and optional object prefix). The serverless template file will get updated during the build to set the CodeUri entries to point to the updated object in S3. The 'Package-only output file' field on the task will be set to something like `$(Build.ArtifactStagingDirectory)\serverless.template`
* Add a Publish Artifacts task to take the staged template from `$(Build.ArtifactStagingDirectory)\serverless.template` and create a drop for your release pipeline. Use the *Server* drop type.

**Release pipeline**
* Use the CloudFormation Create/Update Stack task, pointing the template file option to template file in the incoming drop from the build pipeline.

**Comment by normj** [comment]
I was just working on the switch to global tools the other day. You can check the [global-tools-switch](https://github.com/aws/aws-extensions-for-dotnet-cli/tree/global-tools-switch) branch. 

Your assumption of how these extensions will work as global tools is correct. If you need the tool to do a build it will build the current directory or where ever the `--project-location` switch is pointing to. If you want the tool to do deploy with a prebuilt package use the `--package` switch like you mentioned.

Since global tools can't coexist in the same NuGet package as the existing project style tool the plan is to update all 3 tools in this repository to version 3.0.0. So if somebody needs/wants a project level version they can use a pre 3.0.0 build otherwise you 3.0.0 or greater package.

I have a bit more testing to do and I need to write up some docs/blog post before releasing it. Hopefully I can get that done in the next week or 2 but I'm also in the middle of a few other projects so I can't guarantee any date.

**Comment by melih154** [comment]
Hi @normj,

Just want to check if you think changes on global-tools-switch branch are getting to be merged soon?

**Comment by normj** [comment]
I hope so, I'm finishing up another project right now so I can come back and put the finishing touches/testing on the global tools switch over.

**Comment by normj** [comment]
The Global Tools version of this tool is released. Read [here](https://aws.amazon.com/blogs/developer/net-core-global-tools-for-aws/) for further information.
