### ISSUE TITLE
 deps.json missing when building with SAM CLI a .NET Native AOT project on arm64 architecture

### ISSUE THREAD

**Issue by muku** [aws/aws-extensions-for-dotnet-cli#319]
### Describe the bug

Using SAM CLI to build a .NET 8 Native AOT project doesn't generate the deps.json file which results in a runtime exception when trying to resolve a class from a dependent assembly. I see the following message in the terminal:

`Missing deps.json file. Skipping flattening runtime folder because  is an unrecognized format`

For reference the dependency is AWS.SDK.SQS. 

I have also tried building the hello world project created by running `sam init` and following the steps in the AWS docs. I can see the same message in the terminal as well.

I've seen a similar closed issue and I can confirm that I use the name of the assembly as my function handler in the template.

### Expected Behavior

Generate deps.json when running `sam build`

### Current Behavior

Doesn't generate deps.json

### Reproduction Steps

- `sam init`
- Select AWS Quick Start Templates to choose a starting template.
- Choose the Hello World Example template.
- Choose to not use the most popular runtime and package type by entering n.
- For runtime, choose dotnet8.
- For package type, choose Zip.
- For your starter template, choose Hello World Example using native AOT.
-  `sam build`

### AWS .NET SDK and/or Package version used

SAM CLI 1.118.0

### Targeted .NET Platform

.NET 8 Native AOT

### Operating System and version

OSX Sonoma 14.5 arm64

**Comment by normj** [comment]
Something is off here because a Native AOT deployment should be a zip file of a single executable file. All the assemblies are compiled into the single executable and there is no deps.json file.

Can you do a clean of the `obj` and `bin` folders before deploying in case something is being included into the deployment bundle that shouldn't be? Can you also confirm in the CloudFormation template the `handler` property for the function is set to the assembly name.?
