### ISSUE TITLE
Unable to deploy new Lambda versions with AutoPublishAlias

### ISSUE THREAD

**Issue by scionwest** [aws/aws-extensions-for-dotnet-cli#97]
I have a [serverless template](https://github.com/scionwest/FocusMark/blob/feature/api/projects/src/FocusMark.Api.Projects/serverless.template) that has `AutoPublishAlias` [set to the environment](https://github.com/scionwest/FocusMark/blob/feature/api/projects/src/FocusMark.Api.Projects/serverless.template#L223) name I'm deploying into.

I need to have `AutoPublishAlias` set in order to use `ProvisionedConcurrencyConfig`. However, I can't control the version number of the published Lambda from the serverless resource type. The docs say:

> This AWS SAM property generates two additional resources: an AWS::Lambda::Version resource and an AWS::Lambda::Alias resource.

Since this generates the two additional resources, I'm not able to specify the version number of the Lambda. After I've run `dotnet lambda deploy-serverless` I am unable to run it a second time as a Lambda already exists with the same version number. I don't really want the Alias to change, just the version of the Alias.

> Note: I'm not using Alias to differentiate environments. Dedicated Lambda's are deployed per environment as the resource name includes the environment name. As environment parameter changes, the resource names will as well.

For a working example, you can clone [my feature branch](https://github.com/scionwest/FocusMark/tree/feature/api/projects) and perform the following steps:

- Create S3 bucket called focusmark-dev-deployments
- Run `dotnet lambda publish-layer FocusMarkApiProjectsLayer --layer-type runtime-package-store --s3-bucket focusmark-dev-deployments` from the FocusMark/src/FocusMark.Api.Projects directory
- Update the [aws-lambda-tools-defaults.json](https://github.com/scionwest/FocusMark/blob/feature/api/projects/src/FocusMark.Api.Projects/aws-lambda-tools-defaults.json#L17) file by changing the `LambdaApiLayers` template-parameter with the ARN of the deployed layer above.
- Run `dotnet lambda deploy-serverless` from the FocusMark/src/FocusMark.Api.Projects directory

When completed, change the [provisioned concurrency configuration](https://github.com/scionwest/FocusMark/blob/feature/api/projects/src/FocusMark.Api.Projects/serverless.template#L224) from 2 to 3 and re-run `dotnet lambda deploy-serverless`. The error will report:

> A version for this Lambda function exists ( 1 ). Modify the function to create a new version.

My understanding of how the version number is created is that it generates a hash of the CodeUri & function logical-id. I'm not pre-deploying the Lambda into S3, it's being deployed by the CLI extension. When I download the template pushed to S3 by the CLI, I see the `CodeUri` is set to `s3://<obfuscated-bucket>/<obfuscated-path>/CreateProjectCommand-CodeUri-637114132146239023-637114132179701965.zip` and it changes with each deployment. This should be sufficient for creating a unique hash with each deployment. 

What I think is happening is that my source code isn't changing, just the template in this case as I want to increase the provisioned concurrency. CloudFormation then fails because the version number hash is the same as the code wasn't re-deployed. I don't want to make small changes to the code all the time just to force a new source deployment if that is the case. Are there any recommended work-arounds?

Thanks for any guidance on this!

**Comment by normj** [comment]
I have reproduced the problem and after talking to the SAM team that owns SAM CloudFormation transform that AWS::Serverless::Function defines the resource they said this is an issue they are working. You can track their progress here. https://github.com/awslabs/serverless-application-model/issues/1296

**Comment by tlanghals-uturn** [comment]
Running into this exact same issue after adding AutoPublishAlias so that we can also use ProvisionedConcurrencyConfig.

Running the following after the initial deployment and only updating a description in the SAM template generates a different S3 artifact everytime with identical MD5 resulting in the error above.
``
dotnet-lambda deploy-serverless --s3-bucket example-serverless --stack-name Example-PRD
``

**Comment by jmnarloch** [comment]
Hey @scionwest,

This was a know limitation of [SAM](https://github.com/awslabs/serverless-application-model/pull/1376). The problem was that SAM is not a runtime like CloudFormation it does not have access to resources during the deployment. How SAM is computing the hash of Version to be publish is based on the CodeUri attribute, which is a static path. It will not fetch your artifact and compute the hash out your code base, like AWS Lambda does.

You have two options, either modify the CodeUri, each time and for instance append a build timestamp to it. Or use newly introduced SAM AutoPublishCodeSha256 attribute: https://github.com/awslabs/serverless-application-model/releases/tag/v1.21.0. In both case you will need a post process step in SAM to alter SAM the template file.

**Comment by lisandrolan** [comment]
Hey @jmnarloch , 
Could you provide more detail on how to use AutoPublishCodeSha256?
I could not find much documentation and I having several errors with my template. 

Im using all these properties: 
Properties:
      AutoPublishAlias: live
      AutoPublishCodeSha256: 1db85af3d9db8c7e63dfd243ef6751e665ffabc0452c172be5ab73b5004c2ce4
     
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1
      DeploymentPreference:
        Type: AllAtOnce
